// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scd.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Rate          float32                `protobuf:"fixed32,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CompanyId     string                 `protobuf:"bytes,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ContractorId  string                 `protobuf:"bytes,8,opt,name=contractor_id,json=contractorId,proto3" json:"contractor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_scd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Job) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Job) GetContractorId() string {
	if x != nil {
		return x.ContractorId
	}
	return ""
}

type Timelog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	TimeStart     int64                  `protobuf:"varint,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       int64                  `protobuf:"varint,6,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	JobUid        string                 `protobuf:"bytes,8,opt,name=job_uid,json=jobUid,proto3" json:"job_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timelog) Reset() {
	*x = Timelog{}
	mi := &file_proto_scd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timelog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timelog) ProtoMessage() {}

func (x *Timelog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timelog.ProtoReflect.Descriptor instead.
func (*Timelog) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{1}
}

func (x *Timelog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Timelog) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Timelog) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Timelog) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Timelog) GetTimeStart() int64 {
	if x != nil {
		return x.TimeStart
	}
	return 0
}

func (x *Timelog) GetTimeEnd() int64 {
	if x != nil {
		return x.TimeEnd
	}
	return 0
}

func (x *Timelog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Timelog) GetJobUid() string {
	if x != nil {
		return x.JobUid
	}
	return ""
}

type PaymentLineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	JobUid        string                 `protobuf:"bytes,4,opt,name=job_uid,json=jobUid,proto3" json:"job_uid,omitempty"`
	TimelogUid    string                 `protobuf:"bytes,5,opt,name=timelog_uid,json=timelogUid,proto3" json:"timelog_uid,omitempty"`
	Amount        float32                `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLineItem) Reset() {
	*x = PaymentLineItem{}
	mi := &file_proto_scd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLineItem) ProtoMessage() {}

func (x *PaymentLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLineItem.ProtoReflect.Descriptor instead.
func (*PaymentLineItem) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentLineItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentLineItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PaymentLineItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PaymentLineItem) GetJobUid() string {
	if x != nil {
		return x.JobUid
	}
	return ""
}

func (x *PaymentLineItem) GetTimelogUid() string {
	if x != nil {
		return x.TimelogUid
	}
	return ""
}

func (x *PaymentLineItem) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentLineItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLatestJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestJobsRequest) Reset() {
	*x = GetLatestJobsRequest{}
	mi := &file_proto_scd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestJobsRequest) ProtoMessage() {}

func (x *GetLatestJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestJobsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestJobsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type GetLatestJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestJobsResponse) Reset() {
	*x = GetLatestJobsResponse{}
	mi := &file_proto_scd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestJobsResponse) ProtoMessage() {}

func (x *GetLatestJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestJobsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedFields map[string]string      `protobuf:"bytes,2,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_proto_scd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJobRequest) GetUpdatedFields() map[string]string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

type GetLatestTimelogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeFilter    string                 `protobuf:"bytes,1,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTimelogsRequest) Reset() {
	*x = GetLatestTimelogsRequest{}
	mi := &file_proto_scd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTimelogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTimelogsRequest) ProtoMessage() {}

func (x *GetLatestTimelogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTimelogsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestTimelogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestTimelogsRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

type GetLatestTimelogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timelogs      []*Timelog             `protobuf:"bytes,1,rep,name=timelogs,proto3" json:"timelogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTimelogsResponse) Reset() {
	*x = GetLatestTimelogsResponse{}
	mi := &file_proto_scd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTimelogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTimelogsResponse) ProtoMessage() {}

func (x *GetLatestTimelogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTimelogsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestTimelogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{7}
}

func (x *GetLatestTimelogsResponse) GetTimelogs() []*Timelog {
	if x != nil {
		return x.Timelogs
	}
	return nil
}

type UpdateTimelogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedFields map[string]string      `protobuf:"bytes,2,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimelogRequest) Reset() {
	*x = UpdateTimelogRequest{}
	mi := &file_proto_scd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimelogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimelogRequest) ProtoMessage() {}

func (x *UpdateTimelogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimelogRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimelogRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTimelogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTimelogRequest) GetUpdatedFields() map[string]string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

type GetLatestPaymentLineItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPaymentLineItemsRequest) Reset() {
	*x = GetLatestPaymentLineItemsRequest{}
	mi := &file_proto_scd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPaymentLineItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPaymentLineItemsRequest) ProtoMessage() {}

func (x *GetLatestPaymentLineItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPaymentLineItemsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPaymentLineItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestPaymentLineItemsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type GetLatestPaymentLineItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PaymentLineItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPaymentLineItemsResponse) Reset() {
	*x = GetLatestPaymentLineItemsResponse{}
	mi := &file_proto_scd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPaymentLineItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPaymentLineItemsResponse) ProtoMessage() {}

func (x *GetLatestPaymentLineItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPaymentLineItemsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestPaymentLineItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{10}
}

func (x *GetLatestPaymentLineItemsResponse) GetItems() []*PaymentLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdatePaymentLineItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedFields map[string]string      `protobuf:"bytes,2,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentLineItemRequest) Reset() {
	*x = UpdatePaymentLineItemRequest{}
	mi := &file_proto_scd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentLineItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentLineItemRequest) ProtoMessage() {}

func (x *UpdatePaymentLineItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentLineItemRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentLineItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_scd_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePaymentLineItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePaymentLineItemRequest) GetUpdatedFields() map[string]string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

var File_proto_scd_proto protoreflect.FileDescriptor

const file_proto_scd_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/scd.proto\x12\x03scd\"\xc7\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x02R\x04rate\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"company_id\x18\a \x01(\tR\tcompanyId\x12#\n" +
	"\rcontractor_id\x18\b \x01(\tR\fcontractorId\"\xc8\x01\n" +
	"\aTimelog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x1d\n" +
	"\n" +
	"time_start\x18\x05 \x01(\x03R\ttimeStart\x12\x19\n" +
	"\btime_end\x18\x06 \x01(\x03R\atimeEnd\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x17\n" +
	"\ajob_uid\x18\b \x01(\tR\x06jobUid\"\xb7\x01\n" +
	"\x0fPaymentLineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x17\n" +
	"\ajob_uid\x18\x04 \x01(\tR\x06jobUid\x12\x1f\n" +
	"\vtimelog_uid\x18\x05 \x01(\tR\n" +
	"timelogUid\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\";\n" +
	"\x14GetLatestJobsRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"5\n" +
	"\x15GetLatestJobsResponse\x12\x1c\n" +
	"\x04jobs\x18\x01 \x03(\v2\b.scd.JobR\x04jobs\"\xb5\x01\n" +
	"\x10UpdateJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12O\n" +
	"\x0eupdated_fields\x18\x02 \x03(\v2(.scd.UpdateJobRequest.UpdatedFieldsEntryR\rupdatedFields\x1a@\n" +
	"\x12UpdatedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x18GetLatestTimelogsRequest\x12\x1f\n" +
	"\vtype_filter\x18\x01 \x01(\tR\n" +
	"typeFilter\"E\n" +
	"\x19GetLatestTimelogsResponse\x12(\n" +
	"\btimelogs\x18\x01 \x03(\v2\f.scd.TimelogR\btimelogs\"\xbd\x01\n" +
	"\x14UpdateTimelogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12S\n" +
	"\x0eupdated_fields\x18\x02 \x03(\v2,.scd.UpdateTimelogRequest.UpdatedFieldsEntryR\rupdatedFields\x1a@\n" +
	"\x12UpdatedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	" GetLatestPaymentLineItemsRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"O\n" +
	"!GetLatestPaymentLineItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.scd.PaymentLineItemR\x05items\"\xcd\x01\n" +
	"\x1cUpdatePaymentLineItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12[\n" +
	"\x0eupdated_fields\x18\x02 \x03(\v24.scd.UpdatePaymentLineItemRequest.UpdatedFieldsEntryR\rupdatedFields\x1a@\n" +
	"\x12UpdatedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xce\x03\n" +
	"\n" +
	"SCDService\x12F\n" +
	"\rGetLatestJobs\x12\x19.scd.GetLatestJobsRequest\x1a\x1a.scd.GetLatestJobsResponse\x12,\n" +
	"\tUpdateJob\x12\x15.scd.UpdateJobRequest\x1a\b.scd.Job\x12R\n" +
	"\x11GetLatestTimelogs\x12\x1d.scd.GetLatestTimelogsRequest\x1a\x1e.scd.GetLatestTimelogsResponse\x128\n" +
	"\rUpdateTimelog\x12\x19.scd.UpdateTimelogRequest\x1a\f.scd.Timelog\x12j\n" +
	"\x19GetLatestPaymentLineItems\x12%.scd.GetLatestPaymentLineItemsRequest\x1a&.scd.GetLatestPaymentLineItemsResponse\x12P\n" +
	"\x15UpdatePaymentLineItem\x12!.scd.UpdatePaymentLineItemRequest\x1a\x14.scd.PaymentLineItemB\x13Z\x11genpb/proto;protob\x06proto3"

var (
	file_proto_scd_proto_rawDescOnce sync.Once
	file_proto_scd_proto_rawDescData []byte
)

func file_proto_scd_proto_rawDescGZIP() []byte {
	file_proto_scd_proto_rawDescOnce.Do(func() {
		file_proto_scd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scd_proto_rawDesc), len(file_proto_scd_proto_rawDesc)))
	})
	return file_proto_scd_proto_rawDescData
}

var file_proto_scd_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_scd_proto_goTypes = []any{
	(*Job)(nil),                               // 0: scd.Job
	(*Timelog)(nil),                           // 1: scd.Timelog
	(*PaymentLineItem)(nil),                   // 2: scd.PaymentLineItem
	(*GetLatestJobsRequest)(nil),              // 3: scd.GetLatestJobsRequest
	(*GetLatestJobsResponse)(nil),             // 4: scd.GetLatestJobsResponse
	(*UpdateJobRequest)(nil),                  // 5: scd.UpdateJobRequest
	(*GetLatestTimelogsRequest)(nil),          // 6: scd.GetLatestTimelogsRequest
	(*GetLatestTimelogsResponse)(nil),         // 7: scd.GetLatestTimelogsResponse
	(*UpdateTimelogRequest)(nil),              // 8: scd.UpdateTimelogRequest
	(*GetLatestPaymentLineItemsRequest)(nil),  // 9: scd.GetLatestPaymentLineItemsRequest
	(*GetLatestPaymentLineItemsResponse)(nil), // 10: scd.GetLatestPaymentLineItemsResponse
	(*UpdatePaymentLineItemRequest)(nil),      // 11: scd.UpdatePaymentLineItemRequest
	nil,                                       // 12: scd.UpdateJobRequest.UpdatedFieldsEntry
	nil,                                       // 13: scd.UpdateTimelogRequest.UpdatedFieldsEntry
	nil,                                       // 14: scd.UpdatePaymentLineItemRequest.UpdatedFieldsEntry
}
var file_proto_scd_proto_depIdxs = []int32{
	0,  // 0: scd.GetLatestJobsResponse.jobs:type_name -> scd.Job
	12, // 1: scd.UpdateJobRequest.updated_fields:type_name -> scd.UpdateJobRequest.UpdatedFieldsEntry
	1,  // 2: scd.GetLatestTimelogsResponse.timelogs:type_name -> scd.Timelog
	13, // 3: scd.UpdateTimelogRequest.updated_fields:type_name -> scd.UpdateTimelogRequest.UpdatedFieldsEntry
	2,  // 4: scd.GetLatestPaymentLineItemsResponse.items:type_name -> scd.PaymentLineItem
	14, // 5: scd.UpdatePaymentLineItemRequest.updated_fields:type_name -> scd.UpdatePaymentLineItemRequest.UpdatedFieldsEntry
	3,  // 6: scd.SCDService.GetLatestJobs:input_type -> scd.GetLatestJobsRequest
	5,  // 7: scd.SCDService.UpdateJob:input_type -> scd.UpdateJobRequest
	6,  // 8: scd.SCDService.GetLatestTimelogs:input_type -> scd.GetLatestTimelogsRequest
	8,  // 9: scd.SCDService.UpdateTimelog:input_type -> scd.UpdateTimelogRequest
	9,  // 10: scd.SCDService.GetLatestPaymentLineItems:input_type -> scd.GetLatestPaymentLineItemsRequest
	11, // 11: scd.SCDService.UpdatePaymentLineItem:input_type -> scd.UpdatePaymentLineItemRequest
	4,  // 12: scd.SCDService.GetLatestJobs:output_type -> scd.GetLatestJobsResponse
	0,  // 13: scd.SCDService.UpdateJob:output_type -> scd.Job
	7,  // 14: scd.SCDService.GetLatestTimelogs:output_type -> scd.GetLatestTimelogsResponse
	1,  // 15: scd.SCDService.UpdateTimelog:output_type -> scd.Timelog
	10, // 16: scd.SCDService.GetLatestPaymentLineItems:output_type -> scd.GetLatestPaymentLineItemsResponse
	2,  // 17: scd.SCDService.UpdatePaymentLineItem:output_type -> scd.PaymentLineItem
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_scd_proto_init() }
func file_proto_scd_proto_init() {
	if File_proto_scd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scd_proto_rawDesc), len(file_proto_scd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scd_proto_goTypes,
		DependencyIndexes: file_proto_scd_proto_depIdxs,
		MessageInfos:      file_proto_scd_proto_msgTypes,
	}.Build()
	File_proto_scd_proto = out.File
	file_proto_scd_proto_goTypes = nil
	file_proto_scd_proto_depIdxs = nil
}
